### ISSUE TITLE
fluent_text validator can't handle "null" values in JSON

### ISSUE THREAD

**Issue by metaodi** [ckan/ckanext-fluent#26]
If I try to save a multilingual field, where not all languages are filled and I use "null" values, the fluent_text validator fails with a ValidationError: `invalid type for "en" value`

This is the JSON:

```json
 {"en": null, "fr": "texte"}
```

It works if I use an empty string like that:

```json
 {"en": "", "fr": "texte"}
```

I think the error is caused by [this check if the value is a basestring](https://github.com/ckan/ckanext-fluent/blob/cf9d92ee725df5a5d8e6e29d60c9be86bf162b73/ckanext/fluent/validators.py#L112).

I think "null" values should be ignored or "auto-converted" to empty strings. They are valid in JSON and `json.loads()` converts it to Python's `None`.

Of course I can change the code that sends the request to use empty strings instead of null. But I would consider this a bug. WDYT?

**Comment by wardi** [comment]
If you don't have a language fluent assumes you'd write that as `{"fr": "texte"}` not `{"en":null, "fr":"texte"}`, so the ValidationError is intentional. The way fluent tests for a language is to check `lang in ...`
