### ISSUE TITLE
Using Fluent with CKAN 2.9.2 + yaml Scheming syntax

### ISSUE THREAD

**Issue by ryangermann-gov-on-ca** [ckan/ckanext-fluent#36]
Upgrading to CKAN 2.9.2, the Scheming plugin documentation now shows use of a "yaml" rather than json file format.

Assuming that json will still work but wanting to update to whatever the recommended format is, I'm not sure how to express the "fluent" language info in the yaml format;

JSON looks like this:

    {
      "field_name": "title_translated",
      "preset": "fluent_core_translated",
	  "required": "true",
      "label": {
               "en": "English - Title",
               "fr": "French - Titre"
               },
      "form_placeholder": {
                          "en" : "eg. A descriptive title",
                          "fr" : "par exemple un titre descriptif"
                          }
    },

The Fluent documentation still shows the JSON format.

Is there an example of how this would be expressed in yaml?

**Comment by wardi** [comment]
You can use either JSON or YAML formats now. If you want to convert your JSON to YAML you can use an online converter
